### ISSUE TITLE
Homepage should have single column of text at mobile width

### ISSUE THREAD

**Issue by citizenkade** [yhbrandon/oh-hi#18]
<img width="401" alt="screen shot 2016-08-30 at 6 58 14 pm" src="https://cloud.githubusercontent.com/assets/9668003/18111291/f016132e-6ee3-11e6-9eb5-0153de296de1.png">

**Comment by yhbrandon** [comment]
Fixed in 2092d895a5da12ceed300ae4ec2dc31355ed7729
