### ISSUE TITLE
Footer should expand in height to accommodate additional lines of text at mobile width

### ISSUE THREAD

**Issue by citizenkade** [yhbrandon/oh-hi#19]
<img width="401" alt="screen shot 2016-08-30 at 7 00 25 pm" src="https://cloud.githubusercontent.com/assets/9668003/18111308/1feb4b5a-6ee4-11e6-9570-eb8398104f0e.png">

**Comment by yhbrandon** [comment]
Fixed in 2092d895a5da12ceed300ae4ec2dc31355ed7729
