### ISSUE TITLE
Footer is not stuck to bottom of screen in Safari after scrolling

### ISSUE THREAD

**Issue by citizenkade** [yhbrandon/oh-hi#20]
<img width="1271" alt="screen shot 2016-08-30 at 7 02 14 pm" src="https://cloud.githubusercontent.com/assets/9668003/18111329/5607ac4c-6ee4-11e6-9fc9-11d205a54472.png">

**Comment by yhbrandon** [comment]
Fixed in 2092d895a5da12ceed300ae4ec2dc31355ed7729
