### ISSUE TITLE
Login and Sign Up forms don't load in Safari or mobile Chrome

### ISSUE THREAD

**Issue by citizenkade** [yhbrandon/oh-hi#21]
<img width="781" alt="screen shot 2016-08-30 at 7 05 00 pm" src="https://cloud.githubusercontent.com/assets/9668003/18111374/d6e6f8ae-6ee4-11e6-9686-6770dd9e9050.png">

**Comment by yhbrandon** [comment]
Fixed in 2092d895a5da12ceed300ae4ec2dc31355ed7729
