### ISSUE TITLE
Keep labels floating above text fields when text has been input

### ISSUE THREAD

**Issue by citizenkade** [yhbrandon/oh-hi#25]
Current behavior: after user enters text and text field loses focus, label goes back to placeholder position, overlapping with text.

Expected behavior: label should remain in position, floating above text field.

<img width="484" alt="screen shot 2016-09-25 at 4 24 04 pm" src="https://cloud.githubusercontent.com/assets/9668003/18818362/c3c9a174-833c-11e6-98fb-686faa4724e2.png">

**Comment by yhbrandon** [comment]
Fixed on dev, need to push changes up
