### ISSUE TITLE
Email Verification Message

### ISSUE THREAD

**Issue by yhbrandon** [yhbrandon/oh-hi#34]
#### Description ####

We need to display a message to the user after register for an account that we will send them an email to activate account.

#### Wireframes ####

<img width="538" alt="screen shot 2016-10-11 at 8 49 45 pm" src="https://cloud.githubusercontent.com/assets/1194096/19294674/6174351a-8ff4-11e6-89a6-7dcd2aa6052a.png">

#### Acceptance Criteria ####

  - [ ] Once a user registers, message must be displayed
  - [ ] Must contain link to resend email
  - [ ] Must contain link edit registration from

**Comment by ashwoodall** [comment]
Resend email and edit email links need to be wired up
